### ISSUE TITLE
Wordpress header error after installing

### ISSUE THREAD

**Issue by ninedesign** [bjoernklose/wordpress-api-cors#1]
Hi and thank you for trying to find a solution to the problem. I have installed the plugin on a client site so I can get json data into a mobile app but once installed errors are thrown in the admin as follows:

Warning: Cannot modify header information - headers already sent by (output started at /home/ryanvps/auctionreport.net/wp-content/plugins/wordpress-api-cors-master/wp-json-api-cors.php:1) in
lhome/ryanvps/auctionreport.net/wp-content/pluginslwordpress-apiccors-masterlwp-json-api-cors.php on line 21
Warning: Cannot modify header information - headers already sent by (output started at /home/ryanvps/auctionreportrnet/wp-content/plugins/wordpress-api-cors-master/wp-json-api-cors.php:1) in
lhome/ryanvps/auctionreport.net/wp-contentlplugins/wordpress-api-cors-masterlwp-json-api-cors.php on line 22
Warning: Cannot modify header information - headers already sent by (output started at /home/ryanvps/auctionreport.net/wp-content/plugins/wordpress-api-cors-master/wp-json-api-cors.php:1) in
lhome/ryanvps/auctionreport.netlwp-contentlplugins/wordpress-api-cors-masterlwp-json-api-cors.php on line 23
Warning: Cannot modify header information - headers already sent by (output started at /home/ryanvps/auctionreport.net/wp-content/plugins/wordpress-api-cors-master/wp-json-api-cors.php:1) in
lhome/ryanvps/auctionreport.net/wp-contentlpluginslwordpress-api-cors-masterlwp-json-api-cors.php on line 24

even after removing the few blank lines at the end of the plugin the error remains. Any suggestion? Looking forward to your reply, thanks.

**Comment by bjoernklose** [comment]
Hey!
That seems to be the filter being a bit too general, means it's applied on all pages.
Basically, you could hide the warning message based on your PHP error_reporting settings.

Otherwise, you might want to consider switching to https://github.com/thenbrent/WP-API-CORS, that guy seems to have done a bit more than just copy over from https://github.com/WP-API/WP-API/issues/144#issuecomment-42356295

Hope this helps!

Best wishes
Björn

**Comment by ninedesign** [comment]
Thank you Björn,
so if I understood you’re saying that the plugin is working and those errors can be removed without affecting the site. Just making sure, thanks.

On Feb 26, 2015, at 4:06 AM, Björn Klose notifications@github.com wrote:

> Hey!
> That seems to be the filter being a bit too general, means it's applied on all pages.
> Basically, you could hide the warning message based on your PHP error_reporting settings.
> 
> Otherwise, you might want to consider switching to https://github.com/thenbrent/WP-API-CORS, that guy seems to have done a bit more than just copy over from WP-API/WP-API#144 (comment)
> 
> Hope this helps!
> 
> Best wishes
> Björn
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Stefano Bossi
970.690.7830

**Comment by bjoernklose** [comment]
Yes, should still be working, but I'm not actively using it in production myself.

Best wishes
Björn
